### ISSUE TITLE
Config health and readiness check values

### ISSUE THREAD

**Issue by jrosco** [kiegroup/kie-cloud-operator#644]
Hi, Can/Do we have the ability to change the health and readiness checks values? 

Looking at the current common config I can see this readiness check, for example.

```
readinessProbe:
  httpGet:
    path: /services/rest/server/readycheck
    port: 8080
    scheme: HTTP
  initialDelaySeconds: 30
  timeoutSeconds: 2
  periodSeconds: 5
  failureThreshold: 36
```

Would be great is we can update the values for initialDelaySeconds, timeoutSeconds, periodSeconds and failureThreshold.
