### ISSUE TITLE
Default TrustyAI liveness probe path error

### ISSUE THREAD

**Issue by kkk25641463** [kiegroup/kie-cloud-operator#934]
Currently default  livenessProbe path of TrustyUI  is '/' and trust-ui pod liveness http probe always 404.We must set path to '/audit' 
```
apiVersion: app.kiegroup.org/v1beta1
kind: KogitoSupportingService
metadata:
  name: trusty-ui
spec:
  serviceType: TrustyUI
  replicas: 1
  image: quay.io/kiegroup/kogito-trusty-ui:1.5
  probes:
    readinessProbe:
      httpGet:
        path: '/audit'
        port: 8080
    livenessProbe:
      httpGet:
        host: '/audit'
        port: 8080
    startupProbe:
      httpGet:
        path: '/audit'
        port: 8080
  monitoring:
    path: '/audit'
```
